---
abstract: 'Session plugin for Nephia'
author:
  - 'papix <mail@papix.net>'
build_requires:
  Plack::Builder: 0
  Test::More: 0.98
  Test::Requires: 0
  Test::WWW::Mechanize::PSGI: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.9.0, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nephia-Plugin-PlackSession
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Nephia::Plugin::PlackSession:
    file: lib/Nephia/Plugin/PlackSession.pm
    version: 0.80
requires:
  Nephia: 0.80
  Plack::Middleware::Session: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/nephia/Nephia-Plugin-PlackSession/issues
  homepage: https://github.com/nephia/Nephia-Plugin-PlackSession
  repository: git://github.com/nephia/Nephia-Plugin-PlackSession.git
version: 0.80
